düzenleme

diff --git a/Jenkinsfile.backend-module b/Jenkinsfile.backend-module
--- a/Jenkinsfile.backend-module
+++ b/Jenkinsfile.backend-module
@@ -5,21 +5,13 @@ pipeline {
         }
     }
 
-    parameters {
-        string(
-            name: 'SOURCE_BRANCH',
-            defaultValue: 'backend-module',
-            description: 'Build edilecek branch'
-        )
-    }
-
     stages {
 
         stage('Checkout') {
             steps {
                 checkout([
                     $class: 'GitSCM',
-                    branches: [[name: "*/${params.SOURCE_BRANCH}"]],
+                    branches: [[name: '*/backend-module']],
                     userRemoteConfigs: [[
                         url: 'https://github.com/denizhansan/todo-list.git',
                         credentialsId: 'github-credentials'
@@ -28,11 +20,26 @@ pipeline {
             }
         }
 
+        stage('Read Version') {
+            steps {
+                script {
+                    def versionFile = readYaml file: 'version.yaml'
+
+                    env.BACKEND_VERSION =
+                        versionFile.versions['backend-module'].toString()
+
+                    echo "Backend version: ${env.BACKEND_VERSION}"
+                }
+            }
+        }
+
         stage('Backend Docker Build') {
             steps {
                 dir('backend') {
                     sh '''
-                        docker build -t denizhansan/todo-backend:${BUILD_NUMBER} .
+                        docker build \
+                            -t denizhansan/todo-backend:${BACKEND_VERSION} \
+                            .
                     '''
                 }
             }
@@ -40,17 +47,18 @@ pipeline {
     }
 
     post {
+
         success {
             echo 'Backend module pipeline SUCCESS.'
         }
 
         failure {
-            echo 'Backend module pipeline FAILED'
+            echo 'Backend module pipeline FAILED.'
         }
 
         always {
             sh '''
-                docker image rm denizhansan/todo-backend:${BUILD_NUMBER} || true
+                docker image rm denizhansan/todo-backend:${BACKEND_VERSION} || true
             '''
 
             cleanWs()
